/*
            ----------------------------------------------------------------------------------------------
					CONNECTION: AdventureWorksDW2022, SalesDB

											 SQL EXECUTION PLAN
										      (20:20:30)
				
					1. Basics
					2. HEAP vs CLUSTERED INDEX
					3. NONCLUSTERED INDEX
						 - Scan types
						 - JOIN Algorithms
					4. ROWSTORE vs COLUMNSTORE
					5. SQL Hints
					6. INDEXING STRATEGY
						- Initial Strategy
						- Usage Patterns
						- Scenario-based Indexing
						- Monitoring & Maintenance
			-----------------------------------------------------------------------------------------------
*/


USE AdventureWorksDW2022;
GO

--			********************************************************************************************
--													Pre-Things
--													(20:20:30)
--			********************************************************************************************
-- EXECUTION PLAN:
-- Roeadmap generated by a database on how it will execute your query step by step.

/*
            -----------------------------------------------------------------------------------------------
													BASICS
													(20:23:50)
			-----------------------------------------------------------------------------------------------
*/
SELECT *
INTO FactResellerSales_HP
FROM FactResellerSales;
GO

SELECT *
FROM FactResellerSales_HP;
GO

SELECT *
FROM FactResellerSales;
GO

-- (Display) Estimated Execution Plan [Ctrl + L]:
-- Predicts the excution plan without actually running the query. [Before]

-- Include Actual Execution Plan [Ctrl + M]:
-- Show the execution plan as it occured after running the query [After]

-- Include Live Query Statistics:
-- Shows the real-time execution flow as the query runs. [While]

-- Estimated vs Actual Plans:
-- If the predictions do not match the Actual Execution Plan, 
-- this indicate issues like inaccurate statistics or outdated indexes, leading to poor performance.

-- Table Scan:
-- Reads the entire table, page by page and row by row (everything), 
-- which can lead to slower query performance on large tables.

-- (Clustered) Index Scan:
-- Scans all data in an index to find matching rows.
/*
            -----------------------------------------------------------------------------------------------
													HEAP vs CLUSTERED INDEX
													(20:30:42)
			-----------------------------------------------------------------------------------------------
*/

SELECT *
FROM FactResellerSales
ORDER BY SalesOrderNumber;
GO

SELECT *
FROM FactResellerSales_HP
ORDER BY SalesOrderNumber;
GO

-- TIP:
-- After creating a new INDEX, check the Execution Plan to see if your query uses the index
-- [Execution Plan -> Click on the part to Highlight -> Right click -> Properties ->
-- -> Roll down -> Object -> Index

/*
            -----------------------------------------------------------------------------------------------
													NONCLUSTERED INDEX
													(20:33:22)
			-----------------------------------------------------------------------------------------------
*/

SELECT *
FROM FactResellerSales
WHERE CarrierTrackingNumber = '4911-403C-98';
GO

-- If you want to "vanish" the Key Lookup, you can select only that column
SELECT CarrierTrackingNumber
FROM FactResellerSales
WHERE CarrierTrackingNumber = '4911-403C-98';
GO

SELECT *
FROM FactResellerSales_HP
WHERE CarrierTrackingNumber = '4911-403C-98';
GO

-- ROWSTORE INDEX [Empty]
CREATE NONCLUSTERED INDEX idx_FactReseller_CTA_RS
ON FactResellerSales(CarrierTrackingNumber);
GO

-- Index Seek:
-- A targeted search within an index, retrieving only specific rows.


-- Summary of Scan types:
-- Table Scan: Reads every row in a table. [Worst]
-- Index Scan: Reads all entries in an Index to find results. [Mid]
-- Index Seek: Quickly locates specific rows in an index. [Best]


-- JOIN Algorithms: https://learn.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-join?view=sql-server-ver16
-- Nested Loops: Compares tables row by row. [Best for SMALL tables]
-- Hash Match: Matcches rows using a hash table. [Best for LARGE tables]
-- Merge join: Merge two sorted table. [Efficient when BOTH are sorted]

/*
            -----------------------------------------------------------------------------------------------
													ROWSTORE vs COLUMNSTORE
													(20:393:15)
			-----------------------------------------------------------------------------------------------
*/

SELECT 
	p.EnglishProductName AS ProductName,
	SUM(s.SalesAmount) AS TotalSales
FROM FactResellerSales AS s
INNER JOIN DimProduct AS p
	ON p.ProductKey = s.ProductKey
GROUP BY p.EnglishProductName;
GO

-- Lets see for CLUSTERED COLUMNSTORE INDEX, if it is faster:
-- Use FactResellerSales_HP
SELECT 
	p.EnglishProductName AS ProductName,
	SUM(s.SalesAmount) AS TotalSales
FROM FactResellerSales_HP AS s
INNER JOIN DimProduct AS p
	ON p.ProductKey = s.ProductKey
GROUP BY p.EnglishProductName;
GO

CREATE CLUSTERED COLUMNSTORE INDEX idx_FactResellerSales_HP_CS
ON FactResellerSales_HP;
GO

/*
            -----------------------------------------------------------------------------------------------
													SQL Hints
													(20:45:55)
			-----------------------------------------------------------------------------------------------
*/
-- Commands you add to a query to force the database to run it in a specific way for better performance.
-- https://learn.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-join?view=sql-server-ver16
-- https://learn.microsoft.com/en-us/sql/t-sql/queries/option-clause-transact-sql?view=sql-server-ver16

-- Bad Execution Plan:
--	1. Outdated Statistics
--	2. Too Many Indexes

-- That is SQL Hints for, to help better performance.

USE SalesDB;
GO

-- Execution Plan: You can suggest / force the SQL to use another type of JOIN Algorithm [line: 120] 
-- https://learn.microsoft.com/en-us/sql/t-sql/queries/option-clause-transact-sql?view=sql-server-ver16
-- https://learn.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-table?view=sql-server-ver16
SELECT
	so.Sales,
	sc.Country
FROM Sales.Orders AS so
LEFT JOIN Sales.Customers AS sc WITH(INDEX([PK_customers]))
		ON so.CustomerID = sc.CustomerID
-- OPTION (HASH JOIN);
GO

-- TIPS (20:51:00):
-- Use it very carefully and only if there is like an emergency.
--	1. Test hints in all project environments (DEV, PROD) as performance may vary.
--	2. Hints are quick fixes (workaround not solution). You still have to find the cause and fix it.


/*
            -----------------------------------------------------------------------------------------------
													INDEXING STRATEGY
													(20:52:10)
			-----------------------------------------------------------------------------------------------
*/

-- The GOLDEN RULE: AVOID OVER INDEXING (= LESS is MORE)
--	1. Slows performance
--	2. Confuse Execution Plan (=slows performance)
--	3. Less but more effective INDEXES leads to better performance


-- INDEXES SLOWS DOWN WRTIE PERFORMANCE:
--	When data is inserted, updated or deleted, database has to update indexes

-- Too many INDEXES can confuse Execution Plan:
--	Increase plannint time
--	Choose a suboptimal plan


-- <<<<< #1 Initial Strategy (20:55:25) >>>>>
-- WHat is the MAIN goal of our INDEXING strategy?

-- Mainly 2 types of Databases:

-- OLAP (Online Analytical Processing): 
-- Purpose: BI-, Data-, Report Analitics
-- Use: DWH (Data Warehouse) 
-- Going to be HEAVY READING on this type of DB
-- GOAL: Optimize READ Performance for Data Analytical tools
-- Best type of INDEX: COLUMNSTORE INDEX

-- OLTP (Online Transaction Processing):
-- Purpose: Ecommerce, finance, banking
-- Going to be HEAVY WRITING and READING on this type of DB
-- GOAL: Optimize WRITE (and READ) Performance for Applications
-- Best type of INDEX: CLUSTERED INDEX for each Primary Key

-- What do you want to achieve?
-- Optimize READ Performance
-- Optimize WRITE Performance



-- <<<<< #2 Usage Patterns (21:01:35) >>>>>
--	1. Identify frequently used tables and columns (Q: Most important tables and columns?)
--	2. Choose RIGHT INDEX type
--	3. TEST index


-- <<<<< #3 Scenario-based Indexing (21:05:00) >>>>>
--	1. Identify SLOW queries
--	2. Check Execution Plan
--  3. Choose RIGHT index
--	4. (Test) Compare Execution Plans


-- <<<<< #4 Monitoring & Maintenance (21:05:55) >>>>>
-- Find all in: 24_Indexes.sql [line: 444 - Index Management & Monitoring]
--	1. Monitor Index Usage (DMV - Dynamic Management Views)
--	2. Monitor Missing Indexes
--	3. Monitor Duplicate Indexing
--	4. Update Statistics
--	5. Monitoring Fragmentations

-- <<<<< Indexing Strategy Summary (21:10:10) >>>>>