/*
            ----------------------------------------------------------------------------------------------
					DOC: Project_Notes_Sketches.pdf
					CONNECTION: DataWarehouse

											 Exploratory Data Analysis - EDA
										      (1:03:41:50)

					"Understand Data":
					- Basic Queries
					- Data Profiling
					- Simple Aggregations
					- Subquery
			-----------------------------------------------------------------------------------------------
*/


USE DataWarehouse;
GO

-- ================================================================
--						  Magnitude Analysis
--							(1:04:12:00)
-- ================================================================

-- Compare the measure values by categories.

-- It helps us understand the importance of different categories.

-- <aggr.> [Measure] By [Dimension]
-- Total Sales by Country
-- Total Quantity By Category
-- ...

-- Find the Total Customers by Countries
SELECT
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;
GO

-- Find the Total Customers by Gender
SELECT
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;
GO

SELECT
    gender,
    COUNT(customer_key) AS total_customers,
	ROUND(CAST(COUNT(customer_key) AS FLOAT) / SUM(COUNT(customer_key)) OVER() * 100, 2) AS percent_of_total
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;
GO

-- Find the Total Products by Category
SELECT
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;
GO

-- What is the Average Cost in each Category?
SELECT
	category,
	AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;
GO

-- What is the Total Revenue generated for each Category?
SELECT
	p.category,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
	ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;
GO

-- Find the Total Revenue that is generated by each Customer
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers c
	ON f.customer_key = c.customer_key
GROUP BY
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC;
GO

-- What is the Distribution of sold items across Countries?
SELECT
	c.country,
	SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers c
	ON f.customer_key = c.customer_key
GROUP BY
	c.country
ORDER BY total_sold_items DESC;
GO